### PR TITLE
Feature/building app

### PR DESCRIPTION
**Pull request by MarilenaRoque**
# My Library - Javascript :books:

### Features Built

- Register new Books
- See Registered Books
- Remove Registered Books
- Change the status of registered books

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @MarilenaRoque! You've done an impressive job. :clap: There are just a few adjustments to make in order to complete this project. These include:
- [ ] Keep the application logic separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright)
- [ ] Add the `hint-report` folder to your `.gitignore` file. It doesn't seem to have any relevance to this project. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] __[Optional]__ Add some form validations so that one should not be able to create an empty book

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by MarilenaRoque** [comment]
# Changes Implemented! :robot:
Hello @trekab!
Thank you so much for the review, it pushed me to implement the best practices and I learned a lot developing the changes required.
### I am happy to say that all the requirements are done, including the optional validation. :rocket: 

- [x] Keep the application logic separated from DOM manipulation tasks (screenshot from Pathwright)
- I changed the script for the type module
- I separated the functions and Object logic on a logic.js file and import it into the main script
- I replaced 'onclick' triggers for Event Listeners
- [x]  Add the hint-report folder to your .gitignore file. It doesn't seem to have any relevance to this project. (screenshot from Pathwright)
- I Deleted the unnecessary folder
- [x] [Optional] Add some form validations so that one should not be able to create an empty book
- I Added alert to the page and condition to the responsible function

**Review by MarioDena — APPROVED** [review]
Hello! Great work implementing the requested changes! 🥇 

The project is approved 🟢 

However I would recommend you work a little bit more on a few things:

Optional Changes 🟡 

- [ ] I would work on your presentation, this is a classic portfolio project, and so far the design is lacking (I know this was intentional), give it a nice design since everything is working now this could be a good portfolio project.


Cheers!

**Comment by MarilenaRoque** [comment]
Hey @MarioDena! 

# Thank you so much for the Review! :rocket:
And surely I will work a little bit more on the design to make it look great on my portfolio. 
Great advice!

**Pull request merged**
